[package]
org = "medisafe"
name = "patient.api"
version = "1.0.0"
distribution = "2201.12.3"
keywords = ["Healthcare", "FHIR", "Patient", "r4", "health.fhir.r4.uscore501"]

[build-options]
observabilityIncluded = true
