[package]
org = "wso2"
name = "event_to_fhir"
version = "1.0.0"
distribution = "2201.10.2"
keywords = ["Healthcare", "FHIR", "Patient", "r4", "health.fhir.r4.uscore501"]

[build-options]
observabilityIncluded = true
optimizeDependencyCompilation = true
